#!/bin/bash
# especially for Mountain Lion

echo "Configuration for XCode ..."
sudo xcodebuild -license
sudo xcode-select -switch /Applications/Xcode.app

echo "Don't forget installing Command Line Tools for XCode ..."
open http://developer.apple.com/xcode/

echo "Checking for SSH key, generating one if it doesn't exist ..."
[[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
[[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
open https://github.com/account/ssh

echo "Downloading MacPorts ..."
curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.1.2-10.8-MountainLion.pkg
echo "Installing MacPorts ..."
sudo installer -pkg MacPorts-2.1.2-10.8-MountainLion.pkg

sudo chown -R `whoami` /opt/local

sudo port -v selfupdate

echo "Installing git and bash_completion ..."
sudo port install git-core +bash_completion

echo "
if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
  . /opt/local/etc/profile.d/bash_completion.sh
fi
" >> ~/.bash_profile
source ~/.bash_profile

echo "Installing libyaml openssl sqlite3"
sudo port install libyaml openssl sqlite3 

echo "Installing RVM"
curl -L get.rvm.io | bash -s stable

echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.bash_profile
source ~/.bash_profile

rvm install 1.9.3 --with-openssl-dir=/opt/local --with-opt-dir=/opt/local

# set ruby 1.9.3 as default
rvm use 1.9.3 --default

# add some rules to ~/.gemrc
echo "
install: --no-rdoc --no-ri
update: --no-rdoc --no-ri
" >> ~/.gemrc

echo "Installing Rails ..."
#sudo gem install rails
gem install rails

echo "Installing Bundler to build gem dependencies ..."
gem install bundler

echo "Installing the Heroku gem to interact with the http://heroku.com API ..."
gem install heroku

echo "Installing the pg gem to talk to Postgres databases ..."
gem install pg

# echo "Installing the foreman gem for serving your Rails apps in development mode ..."
# gem install foreman

echo "Installing Pow and Powder, a replacement for WEBricks ..."
gem install powder
powder install

echo "Installing pry, a better replacement for default irb ..."
gem install pry

echo "
export CLICOLOR=1
export GREP_OPTIONS="--color=auto"
# Given characters awared history search
# bind '"\e[A":history-search-backward'
# bind '"\e[B":history-search-forward'
" >> ~/.bash_profile
source  ~/.bash_profile

git config --global color.branch auto
git config --global color.diff auto
git config --global color.status auto

# customized bash prompt
echo "
[[ -s '$HOME/.rvm/contrib/ps1_functions' ]] && source '$HOME/.rvm/contrib/ps1_functions'
ps1_set --prompt ∴
" >> ~/.bash_profile
source  ~/.bash_profile


echo "Done! Chekout current install versions ..."
git version
openssl version
ruby -v
rails -v
